version: 2
registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.DBOT }}
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'fix(dep): '
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    registries:
      - github-npm
    schedule:
      interval: weekly
    commit-message:
      prefix: 'fix(dep): '
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
